/*
 * Interfaz gráfica del programa
 */
package Tombola;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author artur
 */
public class Interfaz extends javax.swing.JFrame {

    Alumno alumnos[] = new Alumno[42];
    int tope = 1;
    DefaultTableModel modelo;
    String arregloTabla[] = new String[2];

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setSize(new Dimension(900, 350));
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/ruleta.png")).getImage());
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre/s");
        modelo.addColumn("Numero de lista");
        this.Tabla.setModel(modelo);
    }

    public void CapturarDatos() {

        if (tope >= 43) {
            JOptionPane.showMessageDialog(null, "Error. Se ha completado la lista");
        } else {
            alumnos[tope] = new Alumno(PantallaNombre.getText(), Integer.parseInt(PantallaNumero.getText()), false);
            arregloTabla[0] = alumnos[tope].nombre;
            arregloTabla[1] = String.valueOf(alumnos[tope].listNum);
            modelo.addRow(arregloTabla);
            tope++;
        }
    }

    protected void guardar() throws IOException {  //Método para guardar en un archivo, los datos de la tabla
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int resultado = fc.showSaveDialog(this);
        if (resultado == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File archivo = fc.getSelectedFile();
        try {
            FileWriter fw = new FileWriter(archivo);
            PrintWriter pw = new PrintWriter(fw);

            for (int i = 0; i < Tabla.getRowCount(); i++) {
                for (int j = 0; j < Tabla.getColumnCount(); j++) {
                    pw.print(Tabla.getValueAt(i, j) + ",");
                }
                pw.println();
            }
            pw.close();
            JOptionPane.showMessageDialog(null, "Archivo guardado con éxito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar el archivo", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    protected void cargar() { //Método para cargar archivos en la tabla
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int resultado = fc.showSaveDialog(this);
        if (resultado == JFileChooser.CANCEL_OPTION) {
            return;
        }

        File archivo = fc.getSelectedFile();

        try {
            FileReader fr = new FileReader(archivo);
            BufferedReader bf = new BufferedReader(fr);
            String linea;
            linea = bf.readLine();
            String[] lista = new String[modelo.getColumnCount()];
            while (linea != null) {
                StringTokenizer st = new StringTokenizer(linea, ",");
                lista[0] = st.nextToken();
                lista[1] = st.nextToken();

                modelo.addRow(lista);
                linea = bf.readLine();
            }
            bf.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al encontrar el archivo en carpeta del proyecto", "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void popBorrarActionPerformed(java.awt.event.ActionEvent evt) {
        int filas = Tabla.getSelectedRow();
        if (filas >= 0) {
            modelo.removeRow(filas);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona la fila a eliminar", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        BorrarFila = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PantallaNombre = new javax.swing.JTextField();
        PantallaNumero = new javax.swing.JTextField();
        BotonAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        BotonCargar = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PantallaResultado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        BorrarFila.setText("Borrar Fila");
        BorrarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarFilaActionPerformed(evt);
            }
        });
        jPopupMenu2.add(BorrarFila);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La Ruleta De La Suerte");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LA RULETA DE LA SUERTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 50));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("NUMERO DE LISTA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        PantallaNombre.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        PantallaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaNombreActionPerformed(evt);
            }
        });
        PantallaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PantallaNombreKeyTyped(evt);
            }
        });
        getContentPane().add(PantallaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 50));

        PantallaNumero.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        PantallaNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PantallaNumeroKeyTyped(evt);
            }
        });
        getContentPane().add(PantallaNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, 50));

        BotonAgregar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BotonAgregar.setText("AGREGAR");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, 40));

        Tabla.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        )
    );
    Tabla.setComponentPopupMenu(jPopupMenu2);
    jScrollPane1.setViewportView(Tabla);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, 310, 260));

    BotonCargar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    BotonCargar.setText("Cargar");
    BotonCargar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BotonCargarActionPerformed(evt);
        }
    });
    getContentPane().add(BotonCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 150, -1));

    BotonGuardar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    BotonGuardar.setText("Guardar");
    BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BotonGuardarActionPerformed(evt);
        }
    });
    getContentPane().add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 150, -1));

    BotonLimpiar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    BotonLimpiar.setText("Limpiar Campos");
    BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BotonLimpiarActionPerformed(evt);
        }
    });
    getContentPane().add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 150, -1));

    BotonBorrar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    BotonBorrar.setText("Borrar Tabla");
    BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BotonBorrarActionPerformed(evt);
        }
    });
    getContentPane().add(BotonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 150, -1));

    jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    jButton1.setText("¡PROBAR SUERTE!");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 160, 40));

    PantallaResultado.setEditable(false);
    PantallaResultado.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    PantallaResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    PantallaResultado.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            PantallaResultadoActionPerformed(evt);
        }
    });
    getContentPane().add(PantallaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 180, 60));

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue.jpg"))); // NOI18N
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, -1, 80));

    jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arturo MTZ\\Desktop\\Equipo\\Tusa-Intrusa\\Tombola\\src\\icons\\pillar.png")); // NOI18N
    getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

    jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arturo MTZ\\Desktop\\Equipo\\Tusa-Intrusa\\Tombola\\src\\icons\\ruleta.png")); // NOI18N
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nube 1.png"))); // NOI18N
    getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

    jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arturo MTZ\\Desktop\\Equipo\\Tusa-Intrusa\\Tombola\\src\\icons\\blue.jpg")); // NOI18N
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 80));

    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nube 1.png"))); // NOI18N
    getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, -1, -1));

    jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nube 1.png"))); // NOI18N
    getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nube 1.png"))); // NOI18N
    getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

    jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cohetes.png"))); // NOI18N
    getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));

    jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arturo MTZ\\Desktop\\Equipo\\Tusa-Intrusa\\Tombola\\src\\icons\\letrero.png")); // NOI18N
    getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

    jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nube 1.png"))); // NOI18N
    getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

    jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nube 1.png"))); // NOI18N
    getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

    jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nube 1.png"))); // NOI18N
    getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

    jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cohetes.png"))); // NOI18N
    getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, -1));

    jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/avion.png"))); // NOI18N
    getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

    jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arturo MTZ\\Desktop\\Equipo\\Tusa-Intrusa\\Tombola\\src\\icons\\blue.jpg")); // NOI18N
    getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -10, 450, 80));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue 2.jpg"))); // NOI18N
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 2620, 1480));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PantallaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaNombreActionPerformed


    }//GEN-LAST:event_PantallaNombreActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        CapturarDatos();
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarActionPerformed
        cargar();
    }//GEN-LAST:event_BotonCargarActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        try {
            guardar();
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed

        if (PantallaNombre.getText().equals("") && PantallaNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No hay nada que limpiar", "Campos Vacios", JOptionPane.WARNING_MESSAGE);
        } else {
            PantallaNombre.setText("");
            PantallaNumero.setText("");
        }
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea borrar todos los datos de la tabla?", "Aviso", JOptionPane.YES_NO_CANCEL_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {

            int filas = Tabla.getRowCount();
            for (int i = 0; i < filas; i++) {
                modelo.removeRow(0);
            }

        }
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void PantallaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PantallaNombreKeyTyped

        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {

            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo LETRAS");

        }

    }//GEN-LAST:event_PantallaNombreKeyTyped

    private void PantallaNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PantallaNumeroKeyTyped

        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo NUMEROS");

        }

    }//GEN-LAST:event_PantallaNumeroKeyTyped

    private void BorrarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarFilaActionPerformed
        int filas = Tabla.getSelectedRow();
        if (filas >= 0) {
            modelo.removeRow(filas);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona la fila a eliminar", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BorrarFilaActionPerformed

    private void PantallaResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaResultadoActionPerformed
            
    }//GEN-LAST:event_PantallaResultadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BorrarFila;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonCargar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JTextField PantallaNombre;
    private javax.swing.JTextField PantallaNumero;
    private javax.swing.JTextField PantallaResultado;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
